apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include (print .Chart.Name ".labels") . | nindent 4 }}
  annotations:
    {{ include (print .Chart.Name ".annotations") . | nindent 4 }}
spec:
  {{- if eq .Values.podCount.type "static" }}
  replicas: {{ .Values.podCount.static }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "component.fullname" . }}
  template:
    metadata:
      labels:
        {{ include (print .Chart.Name ".labels") . | nindent 4 }}
      annotations:
        {{ include (print .Chart.Name ".annotations") . | nindent 4 }}
    spec:
      {{- if .Values.troubleshootingContainer }}
      shareProcessNamespace: true
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.troubleshootingContainer }}
        {{- include "troubleshootingContainer" . | nindent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: {{ include "component.image" . }}
          {{- if .Values.service }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- end }}
          {{- include "probes" . | nindent 10 }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.secrets.enabled }}
          volumeMounts:
            {{- range .Values.secrets.mounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
          {{- end }}
      {{- if .Values.secrets.enabled }}
      volumes:
        {{- range .Values.secrets.mounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
      {{- end }}
